CC = gcc
CFLAGS = -Wall -Wextra -std=c99

TARGETS = Simsek-YT-Lucas-stuff-B23HW2 Simsek-YT-Subirach-stuff-B23HW2

all: $(TARGETS)

Simsek-YT-Lucas-stuff-B23HW2: Simsek-YT-Lucas-stuff-B23HW2.c
	$(CC) $(CFLAGS) -o Simsek-YT-Lucas-stuff-B23HW2 Simsek-YT-Lucas-stuff-B23HW2.c

Simsek-YT-Subirach-stuff-B23HW2: Simsek-YT-Subirach-stuff-B23HW2.c
	$(CC) $(CFLAGS) -o Simsek-YT-Subirach-stuff-B23HW2 Simsek-YT-Subirach-stuff-B23HW2.c

clean:
	rm -f $(TARGETS)
