monsters = ["Bandit", "Blood Hawk", "Camel", "Cultist", "Flying Snake", "Giant Crab", "Giant Rat", "Giant Weasel", "Guard", "Kobold", "Mastiff", "Merfolk", "Mule", "Poisonous Snake", "Pony", "Stirge", "Noble", "Goblin", "Skeleton", "Wolf", "Sprite", "Zombie", "Giant Frog", "Grimlock", "Pseudodragon", "Violet Fungus", "Riding Horse", "Draft Horse", "Axe Beak", "Blink Dog", "Constrictor Snake", "Giant Wolf Spider", "Giant Poisonous Snake", "Bullywug", "Steam Mephit", "Boar", "Panther", "Acolyte", "Lunar Acolyte", "Giant Centipede", "Elk", "Giant Badger", "Giant Bat", "Giant Lizard", "Swarm of Bats", "Swarm of Rats", "Swarm of Ravens", "Flying Sword", "Giant Owl", "Drow", "Dretch", "Worg", "Warhorse Skeleton", "Warhorse", "Thug", "Scout", "Lizardfolk", "Hobgoblin", "Satyr", "Magmin", "Gnoll", "Giant Wasp", "Giant Goat", "Crocodile", "Ape", "Black Bear", "Orc", "Cockatrice", "Turkatrice", "Ice Mephit", "Dust Mephit", "Magma Mephit", "Gray Ooze", "Rust Monster", "Sahuagin", "Darkmantle", "Shadow", "Svirfneblin", "Swarm of Insects", "Brown Bear", "Giant Toad", "Dire Wolf", "Giant Hyena", "Death Dog", "Giant Spider", "Giant Vulture", "Giant Eagle", "Hippogriff", "Imp", "Ghoul", "Harpy", "Brass Dragon Wyrmling", "Animated Armor", "Bugbear", "Spy", "Duergar", "Dryad", "Specter", "Copper Dragon Wyrmling", "Quasit", "Tiger", "Lion", "Swarm of Goblins", "Ankheg", "Awakened Tree", "Black Dragon Wyrmling", "Green Dragon Wyrmling", "White Dragon Wyrmling", "Silver Dragon Wyrmling", "Bronze Dragon Wyrmling", "Ogre", "Berserker", "Bandit Captain", "Centaur", "Giant Boar", "Ogre Zombie", "Gargoyle", "Ettercap", "Grick", "Giant Elk", "Giant Reindeer", "Giant Constrictor Snake", "Griffon", "Saber-Toothed Tiger", "Rhinoceros", "Polar Bear", "Pegasus", "Will-o-Wisp", "Minotaur Skeleton", "Merrow", "Ghast", "Druid", "Cult Fanatic", "Priest", "Azer", "Wererat", "Sea Hag", "Gelatinous Cube", "Gibbering Mouther", "Swarm of Poisonous Snakes", "Mimic", "Plesiosaurus", "Blue Dragon Wyrmling", "Minotaur", "Giant Scorpion", "Hell Hound", "Knight", "Manticore", "Owlbear", "Veteran", "Winter Wolf", "Green Hag", "Wight", "Werewolf", "Nightmare", "Phase Spider", "Mummy", "Basilisk", "Bearded Devil", "Doppleganger", "Gold Dragon Wyrmling", "Elephant", "Red Dragon Wyrmling", "Chuul", "Ettin", "Wereboar", "Weretiger", "Ghost", "Couatl", "Lamia", "Triceratops", "Giant Crocodile", "Hill Giant", "Bulette", "Salamander", "Half-Dragon Veteran", "Gladiator", "Werebear", "Gorgon", "Barbed Devil", "Fire Elemental", "Earth Elemental", "Night Hag", "Shambling Mound", "Otyugh", "Roper", "Troll", "Air Elemental", "Xorn", "Vampire Spawn", "Wraith", "Water Elemental", "Flesh Golem", "Unicorn", "Chimera", "Young White Dragon", "Young Brass Dragon", "Wyvern", "Mammoth", "Vrock", "Medusa", "Drider", "Invisible Stalker", "Mage", "Young Black Dragon", "Young Copper Dragon", "Giant Ape", "Shield Guardian", "Stone Giant", "Oni", "Young Green Dragon", "Young Bronze Dragon", "Tyrannosaurus Rex", "Frost Giant", "Spirit Naga", "Hezrou", "Assassin", "Hydra", "Chain Devil", "Cloaker", "Bone Devil", "Young Blue Dragon", "Young Silver Dragon", "Cloud Giant", "Fire Giant", "Treant", "Clay Golem", "Glabrezu", "Deva", "Young Red Dragon", "Young Gold Dragon", "Young Lunar Dragon", "Stone Golem", "Guardian Naga", "Aboleth", "Roc", "Remorhaz", "Behir", "Gynosphinx", "Horned Devil", "Djinni", "Efreeti", "Dullahan", "Voidling", "Abominable Beauty", "Erinyes", "Archmage", "Winter Wizard", "Gug", "Bear King", "Adult White Dragon", "Adult Brass Dragon", "Storm Giant", "Nalfeshnee", "Vampire", "Adult Black Dragon", "Adult Copper Dragon", "Ice Devil", "Adult Green Dragon", "Adult Bronze Dragon", "Purple Worm", "Mummy Lord", "Adult Blue Dragon", "Adult Silver Dragon", "Planetar", "Marilith", "Iron Golem", "Adult Red Dragon", "Adult Gold Dragon", "Dragon Turtle", "Androsphinx", "Fighter", "Barbarian", "Monk", "Rogue", "Ranger", "Paladin", "Cleric", "Wizard", "Warlock", "NPC Druid", "Sorcerer", "Bard"]
conditions = ["Flying", "True Sight", "Vanilla", "Armored", "Always Reckless", "Boots of Charging", "Magic Resistant", "Zombie", "Evasive", "Smelly", "Starts Invisibile", "Tough", "+2 STR", "+2 DEX", "+2 CON", "+2 INT", "+2 WIS", "+2 CHA", "Good Stats", "Gauntlets of Ogre Power", "Backstabber", "Magic Attacks", "Regenerator", "Projectile Catching", "Strong Grappler", "Wild Element", "Power Attacker", "Diseased", "Blessed By God", "Quick Draw", "Has A Gun", "Fan Favorite", "Fire Attuned", "Cold Attuned", "Lightning Attuned", "Thunder Attuned", "Acid Attuned", "Psychic Attuned", "Force Attuned", "Necrotic Attuned", "Radiant Attuned", "Badly Drawn", "Red Half-Dragon", "Black Half-Dragon", "Green Half-Dragon", "White Half-Dragon", "Blue Half-Dragon", "Reliable Damage", "Crit Master", "Vorpal Blade", "Memorized One Spell", "Mirrored", "Blurred", "Die Hard", "Frenzied", "Electric Body", "Parrier", "Shielded", "Legendary Resistor", "Death Defying", "Skilled", "Natural Heroism", "Overflowing Health"]
MONSTERCOUNT = len(monsters) # 283
CONDITIONCOUNT = len(conditions) # 63
# Turns these into enumerations for easier use elsewhere
MONSTER_ENUM = {name: idx for idx, name in enumerate(monsters)}
CONDITION_ENUM = {name: idx for idx, name in enumerate(conditions)}
MONSTER_ENUM_INV = {idx: name for name, idx in MONSTER_ENUM.items()}
CONDITION_ENUM_INV = {idx: name for name, idx in CONDITION_ENUM.items()}

MONSTER_CR = {
    "Barbarian": 0, # is actually CR -1 but for bracket training purposes we treat as 0. Barbarians are mildly stronger than other -1 CR monsters.
    "Bard": 0,
    "Cleric": 2,
    "Druid": -3,
    "Fighter": -1,
    "Monk": 1,
    "Paladin": 3, # is actually CR 1 but for bracket training purposes we treat as 3. Paladin is just too strong.
    "Ranger": -1,
    "Rogue": 1,
    "Sorcerer": 0,
    "Warlock": 2,
    "Wizard": 1,

    "Bandit": -2,
    "Blood Hawk": -2,
    "Camel": -2,
    "Cultist": -2,
    "Flying Snake": -2,
    "Giant Crab": -2,
    "Giant Rat": -2,
    "Giant Weasel": -2,
    "Guard": -2,
    "Kobold": -2,
    "Mastiff": -2,
    "Merfolk": -2,
    "Mule": -2,
    "Poisonous Snake": -2,
    "Pony": -2,
    "Stirge": -2,
    "Noble": -2,
    "Sprite": -2,
    "Acolyte": -2,
    "Lunar Acolyte": -2,
    "Giant Centipede": -2,

    "Goblin": -1,
    "Skeleton": -1,
    "Wolf": -1,
    "Zombie": -1,
    "Giant Frog": -1,
    "Grimlock": -1,
    "Pseudodragon": -1,
    "Violet Fungus": -1,
    "Riding Horse": -1,
    "Draft Horse": -1,
    "Axe Beak": -1,
    "Blink Dog": -1,
    "Constrictor Snake": -1,
    "Giant Wolf Spider": -1,
    "Giant Poisonous Snake": -1,
    "Bullywug": -1,
    "Steam Mephit": -1,
    "Boar": -1,
    "Panther": -1,
    "Elk": -1,
    "Giant Badger": -1,
    "Giant Bat": -1,
    "Giant Lizard": -1,
    "Swarm of Bats": -1,
    "Swarm of Rats": -1,
    "Flying Sword": -1,
    "Giant Owl": -1,
    "Drow": -1,
    "Dretch": -1,
    "Hobgoblin": -1,
    "Ice Mephit": -1,
    "Dust Mephit": -1,

    "Swarm of Ravens": 0,
    "Worg": 0,
    "Warhorse Skeleton": 0,
    "Warhorse": 0,
    "Thug": 0,
    "Scout": 0,
    "Lizardfolk": 0,
    "Satyr": 0,
    "Magmin": 0,
    "Gnoll": 0,
    "Giant Wasp": 0,
    "Giant Goat": 0,
    "Crocodile": 0,
    "Ape": 0,
    "Black Bear": 0,
    "Orc": 0,
    "Cockatrice": 0,
    "Turkatrice": 0,
    "Magma Mephit": 0,
    "Gray Ooze": 0,
    "Rust Monster": 0,
    "Sahuagin": 0,
    "Darkmantle": 0,
    "Svirfneblin": 0,
    "Swarm of Insects": 0,
    "Quasit": 0,
    "Lion": 0,
    "Wererat": 0,

    "Shadow": 1,
    "Brown Bear": 1,
    "Giant Toad": 1,
    "Dire Wolf": 1,
    "Giant Hyena": 1,
    "Death Dog": 1,
    "Giant Spider": 1,
    "Giant Vulture": 1,
    "Giant Eagle": 1,
    "Hippogriff": 1,
    "Imp": 1,
    "Ghoul": 1,
    "Harpy": 1,
    "Brass Dragon Wyrmling": 1,
    "Bugbear": 1,
    "Spy": 1,
    "Duergar": 1,
    "Dryad": 1,
    "Specter": 1,
    "Copper Dragon Wyrmling": 1,
    "Tiger": 1,
    "Swarm of Goblins": 1,
    "NPC Druid": 1,

    "Animated Armor": 2,
    "Ankheg": 2,
    "Awakened Tree": 2,
    "Black Dragon Wyrmling": 2,
    "Green Dragon Wyrmling": 2,
    "White Dragon Wyrmling": 2,
    "Silver Dragon Wyrmling": 2,
    "Bronze Dragon Wyrmling": 2,
    "Ogre": 2,
    "Berserker": 2,
    "Bandit Captain": 2,
    "Centaur": 2,
    "Giant Boar": 2,
    "Ogre Zombie": 2,
    "Gargoyle": 2,
    "Ettercap": 2,
    "Grick": 2,
    "Giant Elk": 2,
    "Giant Reindeer": 2,
    "Giant Constrictor Snake": 2,
    "Griffon": 2,
    "Saber-Toothed Tiger": 2,
    "Rhinoceros": 2,
    "Polar Bear": 2,
    "Pegasus": 2,
    "Will-o-Wisp": 2,
    "Minotaur Skeleton": 2,
    "Merrow": 2,
    "Ghast": 2,
    "Cult Fanatic": 2,
    "Priest": 2,
    "Azer": 2,
    "Sea Hag": 2,
    "Gelatinous Cube": 2,
    "Gibbering Mouther": 2,
    "Swarm of Poisonous Snakes": 2,
    "Mimic": 2,
    "Plesiosaurus": 2,
    "Wight": 2,
    "Werewolf": 2,

    "Blue Dragon Wyrmling": 3,
    "Minotaur": 3,
    "Giant Scorpion": 3,
    "Hell Hound": 3,
    "Knight": 3,
    "Manticore": 3,
    "Owlbear": 3,
    "Veteran": 3,
    "Winter Wolf": 3,
    "Green Hag": 3,
    "Nightmare": 3,
    "Phase Spider": 3,
    "Mummy": 3,
    "Basilisk": 3,
    "Bearded Devil": 3,
    "Doppleganger": 3,
    "Gold Dragon Wyrmling": 3,

    "Elephant": 4,
    "Red Dragon Wyrmling": 4,
    "Chuul": 4,
    "Ettin": 4,
    "Wereboar": 4,
    "Weretiger": 4,
    "Ghost": 4,
    "Lamia": 4,
    "Triceratops": 4,
    "Half-Dragon Veteran": 4,

    "Giant Crocodile": 5,
    "Hill Giant": 5,
    "Bulette": 5,
    "Gladiator": 5,
    "Werebear": 5,
    "Gorgon": 5,
    "Barbed Devil": 5,
    "Earth Elemental": 5,
    "Night Hag": 5,
    "Shambling Mound": 5,
    "Otyugh": 5,
    "Roper": 5,
    "Troll": 5,
    "Air Elemental": 5,
    "Xorn": 5,
    "Vampire Spawn": 5,
    "Wraith": 5,
    "Water Elemental": 5,
    "Flesh Golem": 5,
    "Unicorn": 5,
    "Wyvern": 5,
    "Cloaker": 5,

    "Couatl": 6,
    "Salamander": 6,
    "Fire Elemental": 6,
    "Chimera": 6,
    "Young Brass Dragon": 6,
    "Mammoth": 6,
    "Vrock": 6,
    "Medusa": 6,
    "Drider": 6,
    "Invisible Stalker": 6,
    "Mage": 6,

    "Young White Dragon": 7,
    "Young Copper Dragon": 7,
    "Giant Ape": 7,
    "Shield Guardian": 7,
    "Stone Giant": 7,
    "Oni": 7,
    "Tyrannosaurus Rex": 7,
    "Spirit Naga": 7,

    "Young Black Dragon": 8,
    "Young Green Dragon": 8,
    "Young Bronze Dragon": 8,
    "Frost Giant": 8,
    "Hezrou": 8,
    "Assassin": 8,
    "Hydra": 8,
    "Chain Devil": 8,

    "Bone Devil": 9,
    "Young Blue Dragon": 9,
    "Young Silver Dragon": 9,
    "Cloud Giant": 9,
    "Fire Giant": 9,
    "Treant": 9,
    "Clay Golem": 9,

    "Deva": 10,
    "Young Red Dragon": 10,
    "Young Gold Dragon": 10,
    "Young Lunar Dragon": 10,
    "Stone Golem": 10,
    "Guardian Naga": 10,
    "Aboleth": 10,

    "Glabrezu": 11,
    "Roc": 11,
    "Remorhaz": 11,
    "Behir": 11,
    "Gynosphinx": 11,
    "Horned Devil": 11,
    "Djinni": 11,
    "Efreeti": 11,
    "Dullahan": 11,
    "Voidling": 11,
    "Abominable Beauty": 11,

    "Erinyes": 12,
    "Archmage": 12,
    "Winter Wizard": 12,
    "Gug": 12,
    "Bear King": 12,

    "Adult White Dragon": 13,
    "Adult Brass Dragon": 13,
    "Storm Giant": 13,
    "Nalfeshnee": 13,
    "Vampire": 13,

    "Adult Black Dragon": 14,
    "Adult Copper Dragon": 14,
    "Ice Devil": 14,

    "Adult Green Dragon": 15,
    "Adult Bronze Dragon": 15,
    "Purple Worm": 15,
    "Mummy Lord": 15,

    "Adult Blue Dragon": 16,
    "Adult Silver Dragon": 16,
    "Planetar": 16,
    "Marilith": 16,
    "Iron Golem": 16,

    "Adult Red Dragon": 17,
    "Adult Gold Dragon": 17,
    "Dragon Turtle": 17,
    "Androsphinx": 17,
}

MONSTERS_BY_CR = {
    "-2": [name for name, cr in MONSTER_CR.items() if cr == -2],
    "-1": [name for name, cr in MONSTER_CR.items() if cr == -1],
    "0": [name for name, cr in MONSTER_CR.items() if cr == 0],
    "1": [name for name, cr in MONSTER_CR.items() if cr == 1],
    "2": [name for name, cr in MONSTER_CR.items() if cr == 2],
    "3": [name for name, cr in MONSTER_CR.items() if cr == 3],
    "4": [name for name, cr in MONSTER_CR.items() if cr == 4],
    "5": [name for name, cr in MONSTER_CR.items() if cr == 5],
    "6": [name for name, cr in MONSTER_CR.items() if cr == 6],
    "7": [name for name, cr in MONSTER_CR.items() if cr == 7],
    "8": [name for name, cr in MONSTER_CR.items() if cr == 8],
    "9": [name for name, cr in MONSTER_CR.items() if cr == 9],
    "10": [name for name, cr in MONSTER_CR.items() if cr == 10],
    "11": [name for name, cr in MONSTER_CR.items() if cr == 11],
    "12": [name for name, cr in MONSTER_CR.items() if cr == 12],
    "13": [name for name, cr in MONSTER_CR.items() if cr == 13],
    "14": [name for name, cr in MONSTER_CR.items() if cr == 14],
    "15": [name for name, cr in MONSTER_CR.items() if cr == 15],
    "16": [name for name, cr in MONSTER_CR.items() if cr == 16],
    "17": [name for name, cr in MONSTER_CR.items() if cr == 17],
}